name: sPaceDan
title: sPaceDan
email: daniel.lorincz@icloud.com
description: UX Development, UI Developer, UX/UI Design, Hardware, Arsenal, Budapest, Beer, Life
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for
twitter_username: dora
github_username:  daniel

#Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _assets/_sass

# Excludes
exclude: ["node_modules", "gulpfile.js", "package.json"]
